CREATE TABLE `participant` (
  `participant_id` int(11) NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(64) CHARACTER SET latin1 NOT NULL,
  `applicant_email` varchar(128) CHARACTER SET latin1 NOT NULL,
  `friend_name` varchar(64) DEFAULT NULL,
  `friend_email` varchar(128) DEFAULT NULL,
  `phonenumber` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `vegan` tinyint(1) NOT NULL,
  `vegetarian` tinyint(1) NOT NULL,
  `english_speaker` tinyint(1) NOT NULL,
  `german_speaker` tinyint(1) NOT NULL,
  `street` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `house_number` int(11) DEFAULT NULL,
  `host` tinyint(1) NOT NULL,
  `appetizer` tinyint(1) NOT NULL,
  `main_course` tinyint(1) NOT NULL,
  `dessert` tinyint(1) NOT NULL,
  `comment` varchar(150) CHARACTER SET latin1 DEFAULT NULL,
  `verified` tinyint(1) NOT NULL DEFAULT '0',
  `paid` tinyint(1) NOT NULL DEFAULT '0',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`participant_id`),
  KEY `friend_email` (`friend_email`),
  KEY `applicant_email` (`applicant_email`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8
